const { SECTION_FLAGS } = require("@lumine-code/sofistik-reader");
const { finitePositive } = require("./values");
const {
  plateNonEffective: PAN_NON_EFFECTIVE,
  polygonNonEffective: PPT_NON_EFFECTIVE,
  polygonInnerBoundary: PPT_INNER_BOUNDARY,
  polygonGeneratedStart: PPT_GENERATED_POLYGON_START,
  plateGenerated: PAN_GENERATED,
} = SECTION_FLAGS;

function rectangleShape(read) {
  if (!read?.count) return null;
  const height = read.columns.h[0];
  const width = read.columns.b[0];
  if (!finitePositive(width) || !finitePositive(height)) return null;
  const type = read.columns.iq[0];
  const flangeThickness = read.columns.ho?.[0];
  const flangeWidth = read.columns.bo?.[0];
  if (
    (type === 2 || type === 3) &&
    finitePositive(flangeThickness) &&
    finitePositive(flangeWidth)
  ) {
    return { kind: "tee", webWidth: width, height, flangeWidth, flangeThickness };
  }
  return { kind: "rectangle", width, height };
}

// One record carries a circle, a ring or a tube, and its second int says which.
function roundShape(read) {
  if (!read?.count) return null;
  const type = read.columns.ir[0];
  const diameter = read.columns.d[0];
  const thickness = read.columns.t[0];
  if (type === 0 || type === 1) {
    if (!finitePositive(diameter) || thickness < 0 || thickness >= diameter) return null;
    return thickness > 0
      ? { kind: "tube", diameter: diameter * 2, thickness: diameter - thickness }
      : { kind: "circle", diameter: diameter * 2 };
  }
  if (type === 2) {
    if (!finitePositive(diameter) || !finitePositive(thickness) || thickness * 2 >= diameter) {
      return null;
    }
    return { kind: "tube", diameter, thickness };
  }
  if (type === 3 && finitePositive(diameter)) return { kind: "circle", diameter };
  return null;
}

// Polygon points carry their polygon number in the high bits of IDP and a
// flag byte below it. Bit 1 marks an inner boundary — a hole — and bit 128 the
// closing vertex, which repeats the first. The rest of the byte is bookkeeping
// about effectiveness, fillets and generation; none of it moves a point, so
// every point is kept whatever it carries. The old reading treated those bits
// as unknown flags and dropped the points wearing them, which lost whole
// areas; it then kept a single polygon of the survivors, which lost the rest
// of a composed section — a plate, a deck and the web between them are three
// polygons of one section.

// Polygons numbered from 100 are generated by the FEM mesh and repeat the
// drawn ones; they stand in only when nothing else is there.

// The polygons a section is drawn from, each with the points it was given and
// whether it is a hole and whether it carries. Read once, because the shape
// and the parts of it that do not count are two questions about one set of
// records.
function sectionPolygons(read) {
  const polygons = new Map();
  for (let index = 0; index < read.count; index += 1) {
    const idp = read.columns.idp[index];
    const number = idp >> 8;
    if (number <= 0) continue;
    const y = read.columns.y[index];
    const z = read.columns.z[index];
    if (!Number.isFinite(y) || !Number.isFinite(z)) continue;
    const entry = polygons.get(number) || {
      number,
      points: [],
      inner: false,
      nonEffective: true,
    };
    if ((idp & PPT_INNER_BOUNDARY) !== 0) entry.inner = true;
    // Every point of an area that does not carry says so, so one that does not
    // say it is enough to make the area count.
    if ((idp & PPT_NON_EFFECTIVE) === 0) entry.nonEffective = false;
    const last = entry.points.at(-1);
    if (!last || last[0] !== y || last[1] !== z) entry.points.push([y, z]);
    polygons.set(number, entry);
  }
  const closed = [...polygons.values()]
    .map((entry) => ({ ...entry, points: stripClosingPoint(entry.points) }))
    .filter((entry) => entry.points.length >= 3);
  const drawn = closed.filter((entry) => entry.number < PPT_GENERATED_POLYGON_START);
  return drawn.length ? drawn : closed;
}

function polygonShape(read) {
  if (!read?.count) return null;
  const usable = sectionPolygons(read);
  const outers = usable
    .filter((entry) => !entry.inner)
    .sort((left, right) => left.number - right.number);
  if (!outers.length) return null;
  const parts = outers.map((entry) => ({ points: entry.points }));
  // A hole belongs to the area it lies inside; one lying in none describes
  // nothing that is drawn.
  for (const hole of usable.filter((entry) => entry.inner)) {
    const target = outers.findIndex((outer) => pointInPolygon(hole.points[0], outer.points));
    if (target < 0) continue;
    (parts[target].holes ||= []).push(hole.points);
  }
  if (parts.length === 1) {
    const only = parts[0];
    const shape = { kind: "polygon", points: only.points };
    if (only.holes) shape.holes = only.holes;
    return shape;
  }
  return { kind: "polygon", parts };
}

function stripClosingPoint(points) {
  const first = points[0];
  const last = points.at(-1);
  return points.length > 1 && first[0] === last[0] && first[1] === last[1]
    ? points.slice(0, -1)
    : points;
}

// Even-odd ray casting, enough to say which area a hole lies inside.
function pointInPolygon(point, polygon) {
  let inside = false;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i, i += 1) {
    const [ay, az] = polygon[i];
    const [by, bz] = polygon[j];
    if (az > point[1] !== bz > point[1]) {
      const crossing = ((by - ay) * (point[1] - az)) / (bz - az) + ay;
      if (point[0] < crossing) inside = !inside;
    }
  }
  return inside;
}

// A thin-walled section is stored as the plates it is welded from: each one a
// run from (ya,za) to (ye,ze) with a thickness, and the run is the plate's
// middle. SOFiSTiK trims them so their bands abut - a girder's web stops at the
// inner face of each flange - so they are passed through as they are stored.
//
// The welds stored beside them are not part of the section. A weld spans the
// gap a plate was trimmed by, so drawing one would put material back where the
// section deliberately has none, and the stored area agrees: it counts the
// plates and not the welds.
//
// A plate SOFiSTiK generated stands in only when nothing was drawn, the same
// rule the generated polygons follow.

// The plates a section is welded from, each with whether it carries. Read once
// for the same reason the polygons are.
function sectionPlates(read, expectedArea = null) {
  const { idp, ya, za, ye, ze, t, wa, we } = read.columns;
  // A release that stored a shorter record leaves out the fields that did not
  // fit, and a plate is its two ends and a thickness or it is nothing at all.
  if (!ya || !za || !ye || !ze || !t) return [];
  const plates = [];
  const generated = [];
  for (let index = 0; index < read.count; index += 1) {
    const thickness = t[index];
    const from = [ya[index], za[index]];
    const to = [ye[index], ze[index]];
    if (!finitePositive(thickness)) continue;
    if (![...from, ...to].every(Number.isFinite)) continue;
    if (from[0] === to[0] && from[1] === to[1]) continue;
    const plate = { from, to, thickness };
    // W0 at both ends of the plate is the cross-section half of the seventh
    // beam degree of freedom. It has units m2; multiplied by d(phi-x)/dx from
    // the result it becomes the axial displacement of this point.
    if (Number.isFinite(wa?.[index]) && Number.isFinite(we?.[index])) {
      plate.unitWarping = [wa[index], we[index]];
    }
    if ((idp?.[index] & PAN_NON_EFFECTIVE) !== 0) plate.nonEffective = true;
    if ((idp?.[index] & PAN_GENERATED) !== 0) generated.push(plate);
    else plates.push(plate);
  }
  return uniquePlates(plates.length ? plates : generated, expectedArea);
}

// Some CDBs repeat the complete panel list byte for byte. Two records naming
// the same band do not describe two layers of material: they occupy the same
// place, and the section's stored area counts the band once. Passing both on
// made the viewer extrude coincident solids; their non-manifold triangle edges
// then appeared as diagonal lines across an otherwise flat member face.
//
// Direction is not identity here. A plate from A to B occupies the same band as
// one from B to A. Thickness remains part of the key because coincident runs of
// different thickness are not the same declared plate.
function uniquePlates(plates, expectedArea) {
  if (!finitePositive(expectedArea)) return plates;
  const material = (items) =>
    items.reduce(
      (total, { from, to, thickness }) =>
        total + Math.hypot(to[0] - from[0], to[1] - from[1]) * thickness,
      0,
    );
  const closeToStoredArea = (area) =>
    Math.abs(area - expectedArea) <= Math.max(1e-9, expectedArea * 1e-5);
  // Coincident plates can be intentional layers. If the list as written
  // already accounts for the section's area, it is not a duplicated list.
  if (closeToStoredArea(material(plates))) return plates;

  const unique = new Map();
  for (const plate of plates) {
    const from = `${plate.from[0]},${plate.from[1]}`;
    const to = `${plate.to[0]},${plate.to[1]}`;
    const ends = from < to ? `${from}|${to}` : `${to}|${from}`;
    const key = `${ends}|${plate.thickness}`;
    const existing = unique.get(key);
    if (!existing) unique.set(key, { ...plate });
    else if (plate.nonEffective) existing.nonEffective = true;
  }
  const deduplicated = [...unique.values()];
  return closeToStoredArea(material(deduplicated)) ? deduplicated : plates;
}

function platesShape(read, expectedArea = null) {
  if (!read?.count) return null;
  const usable = sectionPlates(read, expectedArea).map(({ from, to, thickness, unitWarping }) => ({
    from,
    to,
    thickness,
    ...(unitWarping ? { unitWarping } : {}),
  }));
  return usable.length ? { kind: "plates", plates: usable } : null;
}

// The band a plate occupies: its line offset half a thickness either way,
// square at both ends. The shape hands the viewer the line and the thickness
// and lets it draw the band; an area that does not carry has to be the band
// itself, because that is what the contract asks a section to name.
function plateArea({ from, to, thickness }) {
  const runY = to[0] - from[0];
  const runZ = to[1] - from[1];
  const half = thickness / 2 / Math.hypot(runY, runZ);
  const offsetY = -runZ * half;
  const offsetZ = runY * half;
  return {
    points: [
      [from[0] + offsetY, from[1] + offsetZ],
      [to[0] + offsetY, to[1] + offsetZ],
      [to[0] - offsetY, to[1] - offsetZ],
      [from[0] - offsetY, from[1] - offsetZ],
    ],
  };
}

// The material a section carries in name only. AQUA is given the rule as a NEFF
// window or a NEFF strip and works it through the shape itself, splitting the
// plates and the polygons the boundary crosses and marking the pieces. Those
// marks are what a picture wants: they are already cut to the section, where
// the rule that made them is stated generously enough to reach past it.
//
// Read from whichever records the shape was read from, so the areas and the
// shape can never describe two different sections. The parametric shapes carry
// no marks of their own and get none.
function ineffectiveAreas(shape, read) {
  const areas = [];
  if (shape?.kind === "polygon" && read.polygon?.count) {
    for (const polygon of sectionPolygons(read.polygon)) {
      if (polygon.nonEffective && !polygon.inner) areas.push({ points: polygon.points });
    }
  }
  if (shape?.kind === "plates" && read.panels?.count) {
    for (const plate of sectionPlates(read.panels, read.columns?.a?.[0])) {
      if (plate.nonEffective) areas.push(plateArea(plate));
    }
  }
  return areas.length ? areas : null;
}

// With no shape stored, the section's own area and inertias still describe a
// rectangle of the same stiffness, which is enough to draw it.
function inferredShape(read) {
  if (!read?.count) return null;
  const area = read.columns.a[0];
  const inertiaY = read.columns.iy[0];
  const inertiaZ = read.columns.iz[0];
  if (!finitePositive(area) || !finitePositive(inertiaY) || !finitePositive(inertiaZ)) return null;
  return {
    kind: "rectangle",
    width: Math.sqrt((12 * inertiaZ) / area),
    height: Math.sqrt((12 * inertiaY) / area),
    inferred: true,
  };
}

function readSection(number, read) {
  const section = { id: number, name: `Section ${number}` };
  const area = read.count ? read.columns.a[0] : null;
  const shape =
    rectangleShape(read.rectangle) ||
    roundShape(read.tube) ||
    polygonShape(read.polygon) ||
    platesShape(read.panels, area) ||
    inferredShape(read);
  if (shape) section.shape = shape;
  const ineffective = ineffectiveAreas(shape, read);
  if (ineffective) section.ineffective = ineffective;
  if (read.count) {
    section.area = area;
    section.materialId = read.columns.mno[0];
  }
  return section;
}

module.exports = { readSection, ineffectiveAreas, platesShape, polygonShape, roundShape };
